### ISSUE TITLE
Field mutability should identify external initialization

### ISSUE THREAD

**Issue by errt** [opalj/opal#8]
Taken from Bitbucket#156

> Sometimes, effectively final fields are not initialized via a constructor, but via direct assignments on a newly created, not yet escaped object. This pattern is common e.g. for implementing clone:
```
int i;

public Foo clone(){
Foo f = new Foo();
f.i = i;
return f;
}
````
>Identifying such patters would improve the precision of the field mutability analysis.

**Comment by roterEmil** [comment]
cf. [Test](DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/fixtures/immutability/open_world/assignability/clone_function/SimpleClonePattern.java)
